### ISSUE TITLE
Bug en cas de nom du héro vide 

### ISSUE THREAD

**Issue by BAKFR** [OpMonTeam/OpMon-Archive#10]
Si on appui sur entrée avant de rentrer une lettre à l'écran de choix de nom, on obtiens un nom "buggé".

**Comment by milkyroute** [comment]
Je croyais avoir mis un nom par défaut mais apparement ca ne marche pas, je testerai et je verrai comment corriger.

**Comment by BAKFR** [comment]
OK, plus de précision.

Le nom du héros par défaut est "Céchine", dans le code. Sauf que le fichier de code est en utf-8, et que toutes les chaînes de caractères géré par SFML semblent utiliser l'utf-32 (plein de référence à `toUtf32()` dans le code.

Si c'est possible, je suggère d'utiliser exclusivement de l'UTF-8, qui est le standard en terme d'encoding.

**Comment by milkyroute** [comment]
D'accord, je vais voir pour enlever le bug avec l'accent. Pour le passage en utf-8, je verrai ça plus tard, puisque ça risque de prendre du temps de tout remplacer.

**Comment by Aerzia** [comment]
Le problêm a été corrigé. Désormais le jeu affiche par défault le prénom Pierre. Je ferme l'issue.

**Comment by navet56** [comment]
Non Ethan, c'est céchine, et le bug n'est pas corrigé, Aerzia tu es sur la version 0.12.1 quand tu teste, or il y a eu beaucoup de changement depuis
