### ISSUE TITLE
Enhancement: Change Font to a Pixelated one

### ISSUE THREAD

**Issue by PyroFlareX** [OpMonTeam/OpMon-Archive#100]
[lcd-solid_lcd-solid.zip](https://github.com/OpMonTeam/OpMon/files/3204944/lcd-solid_lcd-solid.zip)

I recommend this one ^

**Comment by milkyroute** [comment]
We will think about it, thanks you! Just, is it copyright free?

**Comment by PyroFlareX** [comment]
It's public domain :P

**Comment by navet56** [comment]
It's done !
