### ISSUE TITLE
Avoid global variables when possible

### ISSUE THREAD

**Issue by Srykah** [OpMonTeam/OpMon-Archive#112]
I see that this code relies heavily on global variables, and to a lesser extent object-global variables. It hinders readability quite a lot, and opens the door to subtle bugs down the road. I am currently cleaning up parts of the code, so I'll do what I can to removve those I find during my refactoring but a large-scale operation seems necessary

**Comment by milkyroute** [comment]
It may be a good idea to do it in the same time as the separation of the engine from the game (#96)
