### ISSUE TITLE
JSON subdivision

### ISSUE THREAD

**Issue by Srykah** [OpMonTeam/OpMon-Archive#117]
JSON files each contain all their respective data (for example, the JSON file for the attacks contains ALL the attacks in the game) ; they should be broken into one file per data item (so, in an `attacks` folder, have a different JSON file for each attack and so on)

This will help readability, ease of contributing and loading times if we ever want to multithread it one day ^^

**Comment by TelloViz** [comment]
This goes along with what I was thinking about the map.json file.

- One map per file

- A table of contents sort of file containing a list of maps (I'm not sure how JSON works..?)

**Comment by Srykah** [comment]
With the help of `std::filesystem` we don't even need a table of contents ^^

**Comment by milkyroute** [comment]
I fixed this with #164 for the maps, we'll see if we split other things but it won't be a problem in the code so I consider this issue fixed.
