### ISSUE TITLE
Remove the data folder from this repo

### ISSUE THREAD

**Issue by Srykah** [OpMonTeam/OpMon-Archive#119]
I see we have a separate repository containing all the game's data, which is a good thing. However, there is still a data folder on this repository as well ; we should remove it, and change the scripts so they can download it from the appropriate source.

**Comment by milkyroute** [comment]
I moved the Resources folder because it was the annex resources, but the data folder is directly used by the program (and by the cmake installer and packager). I don't really see the point of moving it, I must admit.

**Comment by Srykah** [comment]
The main problem is that Git is pretty bad at handling binary files, and changes to them can quickly bloat an archive. Git LFS (Large File Support) is supposed to mitigate that but I don't think it's enabled here. I can try to activate it if you want.

**Comment by Srykah** [comment]
Ok, so I looked into it, and GitHub only provides 1 GB of free LFS storage. Since every modification of a file means the whole file is stored again, we will hit the limit pretty soon.

I have scoured the internet for an answer, and it seems people resort to using cloud services like Dropbox or Google Drive. If we want free hosting (as in freedom) we'll have to either find some free hosting service or host our own (on the same server as the website for example).

I know this issue doesn't seem so bad right now, but trust me : when people will start contributing images and music, pulling will be horrendously long.

**Comment by milkyroute** [comment]
Pulling is already horrendously long, though ^^' And the website doesn't use a dedicated server, I only use github pages in the OpMon-Website repository.
So yes, maybe I should move the data folder to OpMon-Data, but there should be something to download the folder when you want to execute the game for example.

**Comment by olivier-grech** [comment]
Have you thought about using git submodules?

**Comment by Srykah** [comment]
> Have you thought about using git submodules?

Well, there is already a OpMon-Data repository, which should be fine for JSON files, but we need something else for binary files (graphics, music etc.) because they don't work well with Git
