### ISSUE TITLE
Build error on Mac OS X

### ISSUE THREAD

**Issue by martinlehoux** [OpMonTeam/OpMon-Archive#120]
**Steps to reproduce**
OS: macOS Mojave 10.14.6 (18G95) (Le MacBook Pro (Retina, 13 pouces, mi-2014))
```bash
cmake .             #If you want to build in Debug, use -DCMAKE_BUILD_TYPE=Debug
make
sudo make install   # install the game into your system
make package        # generate both .deb package and .tar.gz package
```
**Error**
`make package`
```
CMake Error at /Users/kagamino/Documents/Projets/OpMon/cmake_install.cmake:55 (file):
  file failed to open for writing (Permission denied):

    /Users/kagamino/Documents/Projets/OpMon/install_manifest.txt
```
`ls -la`
`root      staff  23688 27 sep 09:50 install_manifest.txt`
This file seems to have wrong permissions

**Comment by martinlehoux** [comment]
**Solution**
Changing ownership back to my user worked fine

**Comment by milkyroute** [comment]
I've checked permissions on Linux and I have not seen any problem. For now, I'll consider this is as an isolated case, but if something similar happens, don't hesitate to comment here so I will reopen the issue.
