### ISSUE TITLE
Screen Transition Hitbox Issue

### ISSUE THREAD

**Issue by TelloViz** [OpMonTeam/OpMon-Archive#128]
I ventured a ways out of the first town. I talked to a guy about guitar and fences. Then trying to go to the right to the next screen. It seems that the screen transitions too soon.
![OpMonTransition](https://user-images.githubusercontent.com/2664449/69473945-38945e80-0d6f-11ea-9c9c-7ea88150edaa.gif)
![image](https://user-images.githubusercontent.com/2664449/69474166-78107a00-0d72-11ea-881d-35fd50cf9db3.png)

**Comment by TelloViz** [comment]
#129 And one more thing on this topic. When you leave the first area out the path to the right. You cannot turn around and go back to the first town unless you move to the right out of the initial column of tiles where you start.

![OpMonNoEntry](https://user-images.githubusercontent.com/2664449/69474171-8b234a00-0d72-11ea-97b6-073afdb629b7.gif)

**Comment by milkyroute** [comment]
Thank you, I'll fix this soon, it's only some oversights.
