### ISSUE TITLE
Bug de sortie du labo

### ISSUE THREAD

**Issue by navet56** [OpMonTeam/OpMon-Archive#14]
Lorsque le personnage passe la porte de sortie du labo, le TP se fait au mauvaise endroit (1 case en dessous et 1 case sur le coté droit de trop)

**Comment by aerzia-git** [comment]
J'ai essayé de rencontrer le même bug mais je ne détecte absolument rien d'étrange, à part que le splash du labo ext. la porte n'est pas au milieu. Je pense que c'est surtout une histoire de graphisme que de code. Faudrait que tu m'en parle plus en détails.

**Comment by milkyroute** [comment]
Non je confirme ca vient bien du code, il y a juste deux valeurs a changer, mais je n'ai pas le temps en ce moment.

**Comment by navet56** [comment]
Oui Aerzia, essaye d'effectier le TP de façon lente, le bug est bien présent, y a juste 1 ligne de code a changé je vais essayer de voir ça cette aprem
