### ISSUE TITLE
Issue with the "ç" character

### ISSUE THREAD

**Issue by olivier-grech** [OpMonTeam/OpMon-Archive#145]
On the language selection screen, "_Français_" is mispelled as "_Francais_". This is because the "_ç_" character renders as gibberish for an unknown reason.

This is weird because the font (https://www.dafont.com/pixel-arial-11.font) should supports it, and there was no issue with the "_ñ_" character.

I'll try to post a screenshot later on.

**Comment by olivier-grech** [comment]
We probably won't stick with that font, so I suggest closing this issue.

**Comment by milkyroute** [comment]
I'm closing it, it will be reopened if the problem is still here whatever the font is.
