### ISSUE TITLE
Add a wait time in front of the door

### ISSUE THREAD

**Issue by navet56** [OpMonTeam/OpMon-Archive#26]
Ajouter un temps d'attente devant la porte avant de rentrer dans un batiment, car on a pas le temps de voir l'animation de la porte. De plus, ce n'est apas très realiste avec le système actuel.

**Comment by navet56** [comment]
Et egalement un fondu rapide au noir pour pallier au bug de "l'écran bleu"

**Comment by milkyroute** [comment]
This issue has been open for much too long; I close it, and when I'll begin to work on it, I'll reopen it.
