### ISSUE TITLE
Séparation du website et du code du logiciel

### ISSUE THREAD

**Issue by BAKFR** [OpMonTeam/OpMon-Archive#3]
Idéalement, le code HTML et JS contenu dans le dépot devraient être déplacés ailleurs.

**Comment by milkyroute** [comment]
Il n'y a pas de JS dans le dépot, et le index.html a la racine du dépot est nécessaire pour rediriger sur le site (Ce dépot étant hebergé sous downloads.opmon-game.ga). Après, en effet, last.html ne devrait pas exister.

**Comment by milkyroute** [comment]
C'est fait pour last.html! Je supprime downloads.opmon-game.ga et je ferme l'issue.
