### ISSUE TITLE
deb file is not accessible

### ISSUE THREAD

**Issue by sonozaki** [OpMonTeam/OpMon-Archive#30]
The .deb file is not accessible in the downloads section of the web page:

https://github.com/jlppc/OpMon/releases/download/alpha-v0.13/OpMon_0.13-bin.deb

Thanks.

**Comment by navet56** [comment]
I know the problem but

**Comment by navet56** [comment]
I know the problem but we

**Comment by navet56** [comment]
I know the problem but we don't purpose a .deb now sorry, please wait december and the Alpha 0.14 version

**Comment by milkyroute** [comment]
Sorry, my fault, I will try to create the deb as soon as possible.

**Comment by milkyroute** [comment]
You can try to build the game from the source with cmake, while waiting for the deb.

**Comment by sonozaki** [comment]
I'm trying, but 80% gives me this compilation error: 

https://pastebin.com/cqs3xWWc

I do not know if I'm doing something wrong or it's a failure.

Thanks.

**Comment by navet56** [comment]
Hi, please click here : https://github.com/jlppc/OpMon/archive/60c9155858449abb7066629e1e95b4993f707442.zip
Extract the repo
Open a terminal in the new OpMon folder
And write this : 
./build-and-run.sh

**Comment by navet56** [comment]
if it still does not work:
write 

sudo apt install gcc libstdc++6 libsmpeg0 libsfml-dev cmake

in a terminal and retry

**Comment by BAKFR** [comment]
It's because the code use `std::map::try_emplace()`, which is a c++17 feature.
You need to have a more recent c++ compiler.

@jlppc @navet56  maybe we should limit the features we use to c++14 (or c++11) ?

**Comment by navet56** [comment]
It is @gberthou who passed the code in c ++ 17, basic it was in 8, I believe.

**Comment by navet56** [comment]
That's why I propose @sonozaki to play with a version dating from last week, it should work

**Comment by sonozaki** [comment]
Thank you very much! Now, it works for me.

Before I did exactly what you told me but with the .zip that I downloaded from the website and then I tried doing a git clone, with both forms I gave an error. Maybe you should change the .zip of the website because it does not compile.

**Comment by navet56** [comment]
I know, the actual master branch is broken, We are in the middle of refounding the code.
I'm glad it works anyway

**Comment by gberthou** [comment]
We could downgrade to c++11 by using `emplace` instead of `try_emplace`, however code would get more verbose (http://en.cppreference.com/w/cpp/container/map/emplace).
This feature of c++17 is supported in GCC 6. @sonozaki I don't know what version of GCC you're running, but regardless of this project it might be a good idea to upgrade GCC to version 6 or more.
@jlppc If required I can modify the code to use c++11 `emplace`, but I need the source folders to reach a stable state.

**Comment by milkyroute** [comment]
@gberthou I could use macros to define the compiler version and use try_emplace if possible, but if not, just use emplace.

**Comment by gberthou** [comment]
Using only `emplace` everywhere without using macros would be better than using both `emplace` and `try_emplace` with macros.
So the thing is, do you want to support old compilers without c++17 support (*e.g.*, GCC < 6)?

**Comment by milkyroute** [comment]
The .deb is now avilable on the website!
