### ISSUE TITLE
force close on changing language to spanish

### ISSUE THREAD

**Issue by novia713** [OpMonTeam/OpMon-Archive#31]
1. install the game
2. start new game
3. change language to spanish
4. relaunch the app, and happens a force close (windows warns it will close the app)
if i reinstall the game i can play with it until i change to spanish again. once spanish is changed, the force close appears again :-(

perhaps is because i changed language in the middle of a game?
how can i delete the game and after change the language?

**Comment by navet56** [comment]
Which version did you install? On which system? Windows or other?

**Comment by navet56** [comment]
Ok, I just tested, the problem is on all the systems. The bug has been fixed since but we have not released the version yet. I apologize. So either you test the game via sources
Either you wait.
Sorry

**Comment by navet56** [comment]
Please click here to play the game again (but in english sorry) :
https://github.com/jlppc/OpMon/releases/download/alpha-v0.13/OpMon-Win_NoInstall.zip
