### ISSUE TITLE
Clarify art licenses

### ISSUE THREAD

**Issue by IBPX** [OpMonTeam/OpMon-Archive#32]
Hi! It seems some of the art used is incorporated from other projects, but I could not find the appropriate credit anywhere.

For example, [/data/maps/tileset.png](https://raw.githubusercontent.com/jlppc/OpMon/master/data/maps/tileset.png) incorporates "Grass, Sand, Snow" by PastTheFuture, which is licensed as CC BY 4.0, and based on "Kyrodian Legends Overworld Tileset" by Midi. The CC BY license requires that you credit the author, but it seems that isn't being done. If this is not done, you have not fulfilled the license requirements, and are infringing on their copyright, **for which you could be sued.** 

This project's /data/maps/tileset.png (relevant portion in the upper-right):

![/data/maps/tileset.png](https://raw.githubusercontent.com/jlppc/OpMon/master/data/maps/tileset.png)

"Grass, Sand, Snow" by PastTheFuture:

![](https://raw.githubusercontent.com/Tuxemon/Tuxemon/master/tuxemon/resources/gfx/tilesets/PastTheFuture_Grass_Sand_Snow.png)

To avoid legal headache in the future, I recommend keeping a file similar to the [CREDITS.md of the Tuxemon Project](https://github.com/Tuxemon/Tuxemon/blob/master/CREDITS.md) (and [this project's music readme](https://github.com/jlppc/OpMon/blob/master/Resources/Music/README.md) which lists each external resource used by the project, who made it, and what the license is. I would also recommend only using resources licensed under the CC BY and CC BY-SA licenses.

---

Also, the license of this project's own art is unclear. The music is CC BY-SA licensed, but nothing is said about the original art. Without an explicit notice, it could be assumed that the art is also GPLv3 licensed, which is less-than-ideal for art. I would recommend licensing all original art under the CC BY-SA (copyleft) or CC BY (permissive) license.

**Comment by navet56** [comment]
thank you for telling this to me, we try to be precise about the licenses, it will be correct in less than 4 hours

**Comment by navet56** [comment]
It's fixed, thank you
