### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by Chapelier** [OpMonTeam/OpMon-Archive#33]
Seems specials caracters don't work very well in Windows. I've seen the same issue fixed, maybe on Linux or another platform ?

![image](https://user-images.githubusercontent.com/30052777/32985371-aba513ea-ccb9-11e7-9602-36d15c05cf95.png)

**Comment by navet56** [comment]
It's fiex in master branch, please look the "Releases" section on Github in "Things to know"
