### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by BAKFR** [OpMonTeam/OpMon-Archive#36]
*This issue is the first of a serie, aiming to improve the code up to a higher standard. Beware @cyrioncentori, the global variables will go through this!*

As mentioned several times on Discord, We need to choose a coding style.
First, we need to specify most of the aspects we'd like to keep consistent, in order to define the coding style. It's OK if there is a few things unspecified, but the less there is, the better it is.

## Tab VS Spaces

Currently, the code is indented with a mix of 2-space indents (me and Cyrion), and 4-space width tabs (Cyrion).
Other people on Discord were in favor of (4 spaces-width) tab indent.
We could also use Smart Tabs (tabs for indent, then spaces to align when needed). Everyone can set the tab width in its editor.

The choices are:

- 2 spaces
- 4 spaces
- Tabs
- Smart Tabs

## Spaces

No spaces:
```c++
class X{
	X();
};
class Y: X{
	Y();
}

void f(std::vector<Event&> events){
	for(Event *event: events){
		if(event->getPosition().x SQUARES == position.x){
	  		toReturn.push_back(event);
		}else{
			// ... else clause
		}
	}
}
```

Spaces everywhere:
```c++
class X {
	X();
};
class Y: X {
	Y();
}

void f(std::vector<Event&> events) {
	for (Event *event: events) {
		if (event->getPosition().x SQUARES == position.x) {
	  		toReturn.push_back(event);
		} else {
			// ... else clause
		}
}
```

There are spaces (or not):
- Between class name and following curly brace.
- Between keyword (`if`, `for`) and following parenthesis
- Before curly brace on control flow statements (`if`, `for`, etc.)
- before the curly brace opening the function.

## Variable naming

It's probably the only point we have some coherence. All code use the same style.

```c++
class Foo{
public:
	void barBaz();
	int classVariable;
};


void Foo::barBaz(){
	int myVariable;
}
```
However, we may improve it by using a `_` suffix for private and protected variables. In practice, almost all class variables are private or protected.

```c++
class Foo{
protected:
	int _myVar;
};
```

## Should we indent `case` in `switch` statements ?

```c++
switch(layer){
case 1:
	return layer1[pos.x + pos.y * w] - 1;
case 2:
	return layer2[pos.x + pos.y * w] - 1;
case 3:
	return layer3[pos.x + pos.y * w] - 1;
default:
	return 0;
}
```

```c++
switch(layer){
	case 1:
		return layer1[pos.x + pos.y * w] - 1;
	case 2:
		return layer2[pos.x + pos.y * w] - 1;
	case 3:
		return layer3[pos.x + pos.y * w] - 1;
	default:
		return 0;
}
```

## Classes

Should we indent `public`, `private` and `protected` ?

```c++
class Map {
private:
	const int *layer1;

public:
	sf::Vector2i getDimensions() const;
};
```

```c++
class Map {
	private:
	const int *layer1;

	public:
	sf::Vector2i getDimensions() const;
};
```

## Should we indent the namespaces ?

Currently, we do it everywhere, but we may waste less space by removing it.

----

My preferences:
- Tab vs spaces:	SmartTabs
- Spaces between class name and following curly brace:	Yes
- Spaces between keyword (`if`, `for`) and following parenthesis:	no preference
- Spaces before curly brace on control flow statements (`if`, `for`, etc.):	Yes
- Spaces before the curly brace opening the function:	yes
- Using `_` prefix for private member variables: Yes
- Should we indent `case` in `switch` statements ?	No
- Should we indent `public`, `private` and `protected` ?	no preference
- Should we indent the namespaces ?	No preference

In any case, I care way more to keep the code consistent than to use my preferred coding style.

**Comment by milkyroute** [comment]
Ok I will anwser using the same model as you : 
 - Tab vs spaces: SmartTabs (I think it is a good idea)
 - Spaces between class name and following curly brace: Yes (That is what I want to do since the beginning but I forget to add the space each time a add a curly brace)
 - Spaces between keyword (if, for) and following parenthesis: No
 - Spaces before curly brace on control flow statements (if, for, etc.): Yes
 - Spaces before the curly brace opening the function: Yes
 - Using _ prefix for private member variables: The programmer chooses. I won't use it myself, but if somebody is used to do this, I don't have any problems with it. Do what you want.
 - Should we indent case in switch statements ? No
 - Should we indent public, private and protected ? No
 - Should we indent the namespaces ? Yes (It's more organized like that, and the code seems more "ventilated")
