### ISSUE TITLE
character locked on start position

### ISSUE THREAD

**Issue by sonozaki** [OpMonTeam/OpMon-Archive#38]
I installed opmon compiling it and generating the .deb in debian 9.
When I play a new game, the character stays locked in the initial position, I can not move anywhere.

Thanks.

**Comment by sonozaki** [comment]
This is the position where it is blocked:

![captura de pantalla_2018-02-02_10-14-46](https://user-images.githubusercontent.com/27778483/35725526-eede5350-0801-11e8-88e6-455696f73776.png)

**Comment by navet56** [comment]
Yes it's normal for now :wink:

**Comment by navet56** [comment]
Please wait sunday

**Comment by navet56** [comment]
Fixed
