### ISSUE TITLE
Windows 8.1 OpMon v0.14 - Pop up screen doesn't show up

### ISSUE THREAD

**Issue by ghost** [OpMonTeam/OpMon-Archive#39]
Here is a link to the youtube video of what happens: https://youtu.be/bl_5Ypc3AZw

**Comment by ghost** [comment]
//temporary fix: startscenectrl.cpp
if(event.key.code == sf::Keyboard::Return){// && startscene.getPart() == 1) {
                    sf::String &pName = startscene.getpName();
                    if(pName.isEmpty()) {
                        pName = "Player";
                    }
					view.draw(View::frame);
					startscene.delLoop1();
                    _next_gs = new AnimationCtrl(new View::Animations::WinAnim(View::frame.getTexture(), false));
                    return GameStatus::NEXT;
                }

NOTE: When I press Enter for frames 1 through 5 the name screen shows up.  For frame 6("what is your name?") if I never press Space then the name screen shows up when I press Enter.

**Comment by milkyroute** [comment]
As I see it, the problem seems coming from the animation. I will check this out this week-end.

**Comment by ghost** [comment]
The problem seems to be coming from the variable part in StartScene.cpp.  

A new branch was created: https://github.com/cyrioncentori/OpMon/tree/fix39

**Comment by GReaperEx** [comment]
Does the bug still persist? I'm asking because there's no such problem when I compile the game from source in Ubuntu. If it does, maybe it's some form of undefined or implementation-defined behaviour that's only present with Windows 8.1

For example, I have noticed that SDL handles key-presses slightly differently in Windows vs Linux, by always sending key-ups immediately after key-downs for many keys (in Linux). Maybe SFML has a similar problem...

**Comment by navet56** [comment]
This bug is specific to some Windows PCs, and yes the problem probably comes from SFML but can maybe be adjusted by changing the code, we'll be looking into the problem soon.

**Comment by milkyroute** [comment]
@rjphares Can you try to compile the game now ? Is the bug still here ?

**Comment by ghost** [comment]
After a couple compilation errors (similar to the build before the last build - had to make adjustments to WINMAIN and commented out OpMon version) I was able to compile successfully. 

Here are the log errors:
[T = 312] - Error  nÂ°1 : Failed to load music: audio/music/wildbattle.ogg
[T = 1290] - Error  nÂ°2 : Failed to load resource: backgrounds/dialog/battle_dialog.png
[T = 1297] - Error  nÂ°3 : Failed to load resource: sprites/misc/arrBattle.png
[T = 1304] - Error  nÂ°4 : Failed to load resource: sprites/chara/cyrion/cyrion.png
[T = 1312] - Error  nÂ°5 : Failed to load resource: sprites/battle/square_2.png
[T = 1323] - Error  nÂ°6 : Failed to load resource: sprites/battle/shadow_2.png
[T = 1328] - Error  nÂ°7 : Failed to load resource: sprites/battle/shadow_1.png
[T = 1344] - Error  nÂ°8 : Failed to load resource: backgrounds/dialog/attacks_dialog.png
[T = 1350] - Error  nÂ°9 : Failed to load resource: sprites/battle/types/BAD.png
[T = 1354] - Error  nÂ°10 : Failed to load resource: sprites/battle/types/BUG.png
[T = 1357] - Error  nÂ°11 : Failed to load resource: sprites/battle/types/BURNING.png
[T = 1361] - Error  nÂ°12 : Failed to load resource: sprites/battle/types/COLD.png
[T = 1364] - Error  nÂ°13 : Failed to load resource: sprites/battle/types/DRAGON.png
[T = 1367] - Error  nÂ°14 : Failed to load resource: sprites/battle/types/ELECTRON.png
[T = 1372] - Error  nÂ°15 : Failed to load resource: sprites/battle/types/FIGHT.png
[T = 1376] - Error  nÂ°16 : Failed to load resource: sprites/battle/types/GHOST.png
[T = 1379] - Error  nÂ°17 : Failed to load resource: sprites/battle/types/GROUND.png
[T = 1382] - Error  nÂ°18 : Failed to load resource: sprites/battle/types/LIQUID.png
[T = 1386] - Error  nÂ°19 : Failed to load resource: sprites/battle/types/MAGIC.png
[T = 1389] - Error  nÂ°20 : Failed to load resource: sprites/battle/types/MENTAL.png
[T = 1394] - Error  nÂ°21 : Failed to load resource: sprites/battle/types/METAL.png
[T = 1400] - Too many errors. Closing program. Please verify your installation. If the problems persists, warn us.
[T = 1400] - Fatal error. Total errors : 21

**Comment by milkyroute** [comment]
This problem comes from the resources, your "data" repertory is too old. I think you forgot to update it.

**Comment by ghost** [comment]
I feel stupid. Should have known better. But it works now. Thank you.
