### ISSUE TITLE
 Provide a way to verify download file 

### ISSUE THREAD

**Issue by WPFilmmaker** [OpMonTeam/OpMon-Archive#41]
A sha256sum or gpg would be nice in order to verify that the downloaded file from opmon-game.ga has not been tampered by a malicious attacker.

**Comment by milkyroute** [comment]
sha256 and md5 are avilable on the releases. But I should mention that in the website. Thanks for noticing.

**Comment by WPFilmmaker** [comment]
@cyrioncentori Thanks a lot! It would be great having them on the website (similarly to how The Secret Chronicles of Dr. M. does).

**Comment by navet56** [comment]
Done ✓
