### ISSUE TITLE
Https for opmon-game.ga

### ISSUE THREAD

**Issue by WPFilmmaker** [OpMonTeam/OpMon-Archive#42]
At the moment opmon-game.ga does not uses HTTPS (not even for the download page). Switching to HTTPS would provide security for the user and would make the site future-proof (both Firefox and Chrome are enabling tactics to warn users against non secure websites).

**Comment by milkyroute** [comment]
I will research how to do this.

**Comment by WPFilmmaker** [comment]
Thanks!

**Comment by navet56** [comment]
Thanks for taking an interest in the project anyway ! :+1:

**Comment by WPFilmmaker** [comment]
You are welcome! I am testing the game I will definitively report feedbacks n the future ;)

**Comment by navet56** [comment]
That's nice of you !

**Comment by navet56** [comment]
https://www.ovh.com/fr/ssl-gateway/

**Comment by milkyroute** [comment]
@WPFilmmaker Done!
