### ISSUE TITLE
What is the license of arts in the game? (Question)

### ISSUE THREAD

**Issue by WPFilmmaker** [OpMonTeam/OpMon-Archive#43]
Hi, I have a question about the graphics in the game. They are so good that I can't understand whether they come from a copyrighted game (therefore not free) or if you made them. If you made them compliments! If they are not free I hope they will eventually be replaced by free graphics.

**Comment by navet56** [comment]
The game art is totally free, please check [here](https://github.com/cyrioncentori/OpMon/blob/master/Resources/README.md) for more informations
