### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by GReaperEx** [OpMonTeam/OpMon-Archive#45]
I know this game is far from finished but I think volume control should be added as soon as possible. It's not always convenient to lower the whole system's volume in order not to have the game play at eardrum-tearing levels.

As it stands now, the volume slider is only visual and does nothing, unless I'm missing something.

**Comment by milkyroute** [comment]
Thanks for helping, even if the feature is planned. And yes, for now, the volume slider is only visual, but the volume function is programmed. The only things left is to make the volume editable, because right now it is a constant, and make the slider functional. I will work on it when I will work on it when the issue #39 will be solved, after the work on the battle. However, I will try to add a way to change the volume by changing a value in the parameters file as soon as possible.

**Comment by navet56** [comment]
You can see what we have planned to add for the next version here https://github.com/OpMonTeam/OpMon/projects/3

**Comment by Samurai413x** [comment]
I have a partial, placeholder fix for this if you're interested.  It doesn't affect the sounds, only the music, and you can only lower the volume to 1, not all the way to 0.  Also, the slider UI element does not change.  But it still gets the job done!

Let me know if you want me to submit a PR for this fix.  I have some ideas for a more robust implementation, but I need to think through them a bit more.

**Comment by milkyroute** [comment]
Thank you very much, but I have already a solution to control the global volume (src/opmon/view/Jukebox.[ch]pp), I just need to make it editable by the user. However, if you think your system is better, feel free to submit a pull request !

**Comment by GReaperEx** [comment]
The sound effects are scattered all throughout the source, it won't be easy to control their volume...
I suggest a redesign, where all sounds are loaded inside a static class (or namespace, for that matter) that can control volume, among other things. Say, "SoundCtrl" for sound effects and "MusicCtrl" for music, if you want to keep them separate. Then they would just return references to the sounds each object requires simply by asking for them by name. For example:
```
SoundCtrl::addSound("door", "data/audio/sounds/door.ogg");
...
SoundCtrl::getSound("door").play();
```

**Comment by milkyroute** [comment]
I have already that : [Jukebox.hpp](https://github.com/OpMonTeam/OpMon/blob/master/src/opmon/view/Jukebox.hpp) | [Jukebox.cpp](https://github.com/OpMonTeam/OpMon/blob/master/src/opmon/view/Jukebox.cpp)  
But it's only for the musics, I should add the sounds too.

**Comment by Samurai413x** [comment]
> Thank you very much, but I have already a solution to control the global volume (src/opmon/view/Jukebox.[ch]pp), I just need to make it editable by the user. 

Yep! This is what I used.  Basically pressing left / right arrow on the Music row of the Option menu changes that global volume inside Jukebox.  I'll submit a PR so you can see what I mean.

**Comment by milkyroute** [comment]
Oh, thank you! I am very intrested in your pull request.

**Comment by milkyroute** [comment]
Issue fixed in glob_vars branch. I will close it when it will be merged with master.
