### ISSUE TITLE
Crash at the exit of the OpCenter

### ISSUE THREAD

**Issue by navet56** [OpMonTeam/OpMon-Archive#46]
"core dumped"

**Comment by GReaperEx** [comment]
I'm sorry but unless you tell us what you did before exiting the OpCenter, we won't be able to reproduce it. Simply entering and exiting doesn't crash.
( Btw, by "OpCenter" I assumed you meant the Lab, because there is no OpCenter )

**Comment by GReaperEx** [comment]
Can you show us the errLog.txt and log.txt files? Maybe there's something there that'll help us figure out what went wrong.

**Comment by milkyroute** [comment]
The OpCenter is not the laboratory, but an equivalent to the Pokemon Center in "Mysterious City" (A lavender-town like city, it's a test city, hidden from the rest of the game). You can access it in the debug mode by pressing F8.
