### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by GReaperEx** [OpMonTeam/OpMon-Archive#47]
I'm searching through the directories but I can't find any config file, for example one which would define default values for window size, volume, vsync, fullscreen and others. That could potentially be changed by the player while in the options screen (or manually) and saved for the next time they open the game.

So, for example, if I wanted my game to always open with 25% volume, at fullscreen and with vsync off, the config file would be like:
```
volume:25
fullscreen:true
vsync:false
```

**Comment by milkyroute** [comment]
There is one, depending on your location. On windows, it is quite simple to find : it is in the game's repertory. On Linux, it is normally located in ~/.config/OpMon/saves/optSave.oparams. Here is the list of the options currently created : 
- Game base controls
- Language
- Fullscreen

**Comment by GReaperEx** [comment]
Yes, found it. Sorry about that, I should be more observant.
