### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by jubalh** [OpMonTeam/OpMon-Archive#52]
I just installed opmon and get a very wird behaviour which might be a problem on my side. But I think I will need your help to track it down.

I launch opmon in a terminal and I get:
```
$ opmon
Error n°1 : Keys initialization error: keys/english.rkeys
Fatal error.
```
No window is displayed. Program exits.

Funny enough I have another terminal instance open in which case it launches opmon when I type the name.

For both  I get:
````
which opmon
/usr/bin/opmon
````

So it's the same executable.
When starting over the desktop file in GNOME3 menu it also doesn't start (which is the reason I went to the terminal in the first place).

So my question: under which circumstance is this error message displayed?

**Comment by jubalh** [comment]
```
rpm -ql opmon|grep keys                                                                                                                                              
/usr/share/OpMon/keys
/usr/share/OpMon/keys/english.rkeys
/usr/share/OpMon/keys/espanol.rkeys
/usr/share/OpMon/keys/francais.rkeys
```

Keys are installed in that location.

**Comment by navet56** [comment]
How did you install the game? Normally this is not where the data is installed

**Comment by jubalh** [comment]
I'm packaging the game right now as an rpm for openSUSE.
AFAIK this is where it should be installed.

I'm using the openSUSE Cmake macro.
Which expands to:
```
    find . -name CMakeLists.txt \
        -exec sed -i -re '/^[[:blank:]]*[sS][eE][tT][[:blank:]]*\([[:blank:]]*(CMAKE_BUILD_TYPE|CMAKE_COLOR_MAKEFILE|CMAKE_INSTALL_PREFIX|CMAKE_VERBOSE_MAKEFILE).*\)/{s/^/#IGNORE /}' {} + 
    mkdir -p build 
    cd build 
    /usr/bin/cmake $OLDPWD/. \
%if "/usr/bin/make" == "/usr/bin/make" 
        -G"Unix Makefiles" \
%else 
        -GNinja \
%endif 
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
        -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64 \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_C_FLAGS="${CFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_CXX_FLAGS="${CXXFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_Fortran_FLAGS="${FFLAGS:--O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables} -DNDEBUG" \
        -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
        -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed" \
        -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DCMAKE_SKIP_RPATH:BOOL=ON \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=ON \
        -DBUILD_STATIC_LIBS:BOOL=OFF \
        -DCMAKE_COLOR_MAKEFILE:BOOL=OFF \
        -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
        -DCMAKE_MODULES_INSTALL_DIR=/usr/share/cmake/Modules
```

Thus setting the prefix to /usr

**Comment by jubalh** [comment]
Ok, I understand now why it works in that one terminal.
It's the instance where I am in the checked out git repo ;)
So it just takes the resources relative to pwd.

I think opmon needs to be patched to look for the location in the official places (/usr/local/share and /usr/share). It would be best if one could use the value that was given to it via CMake. Not sure if or how that is possible.

**Comment by jubalh** [comment]
Shouldnt https://github.com/OpMonTeam/OpMon/blob/master/src/utils/path.cpp#L92 do this?

BTW I'm using the 0.14 release tarball. But according to git blame it already contains this.

**Comment by jubalh** [comment]
Okay give me a minute, I might be on it ;)

**Comment by jubalh** [comment]
Solved it :)
