### ISSUE TITLE
openSUSE package

### ISSUE THREAD

**Issue by jubalh** [OpMonTeam/OpMon-Archive#56]
I created an rpm package for openSUSE.

I would like to note it down somewhere in your repo so that users can easily find out about it and install it.

So far it seems you uploaded an Arch PKGBUILD to the releases.

Do you think an `INSTALL.md` file would be a good thing? And describing various installation methods and links to available packages there?

**Comment by navet56** [comment]
Wow thank you very much for creating this package! We wanted one but no one used this distribution. And of course, there are all the installation instructions in the wiki : https://github.com/OpMonTeam/OpMon/wiki/Compilation
Anyway thank you very much for everything you do for the game

**Comment by navet56** [comment]
So, put the instructions to create an openSuse package here, and the compiled file in the wiki if you can, either by email: evandib@gmail.com

**Comment by jubalh** [comment]
Ok. openSUSE users can add my private repo and install OpMon like this:

```
zypper ar -f obs://home:jubalh jubalh
zypper ref
zypper in opmon
```

The rpms can currently be downloaded here: https://build.opensuse.org/package/binaries/home:jubalh/opmon/openSUSE_Leap_15.0

Here you can see recipe for building the rpm: https://build.opensuse.org/package/show/home:jubalh/opmon

However I plan to push OpMan into the openSUSE games devel project, it is more official than a private repo.
From there it can go into the official distribution packages once it is in good shape.

**Comment by navet56** [comment]
Thanks for your help, an openSUSE section has been added in the Compilation page on the wiki : https://github.com/OpMonTeam/OpMon/wiki/Compilation#opensuse-installation

**Comment by jubalh** [comment]
Great :)

**Comment by jubalh** [comment]
OpMon got accepted into the `games` devel repo. I adjusted the wiki page at https://github.com/OpMonTeam/OpMon/wiki/Compilation#opensuse-installation

**Comment by navet56** [comment]
Really cool ! Thank you
