### ISSUE TITLE
Mentioning openSUSE

### ISSUE THREAD

**Issue by jubalh** [OpMonTeam/OpMon-Archive#80]
Hello!
It would be super cool that when you create a new release and mention how to install it on different distrubtions that you could also mention the openSUSE distro. We have an always up to date package at: https://build.opensuse.org/package/show/games/opmon :-)

**Comment by milkyroute** [comment]
Oh ! Sorry, we have forgotten ! One of us will do as soon as possible.

**Comment by jubalh** [comment]
No problem :) Just for the future

**Comment by milkyroute** [comment]
Done !

**Comment by jubalh** [comment]
Thanks!
