### ISSUE TITLE
Créer le fichier log s'il n'existe pas

### ISSUE THREAD

**Issue by BAKFR** [OpMonTeam/OpMon-Archive#9]
Au 1er lancement (sous Linux), le programme plante car il n'y a pas de fichiers de log ... mais créé le fichier de log. 
Au 2ème lancement, tout va bien puisque le dossier a été créé.

Le programme devrait créer le dossier avant de tester l'ouverture des fichiers de log

**Comment by milkyroute** [comment]
Ah oui, je ne sais pas pourquoi, je l'ai fait sous windows et j'ai oublié sous linux. Je le ferai
