### ISSUE TITLE
Enhancement: Isolate Engine from Game

### ISSUE THREAD

**Issue by PyroFlareX** [OpMonTeam/OpMon-Archive#96]
To futureproof the work the has been done, I believe it would be wise to isolate the engine and the game. The engine has all the game logic and loaders, while the game would be the assets, maps, OpMon, text boxes, etc. The Engine would load a folder which is where the game assets would be placed in a standardized format.
EX: File Structure
----RootFolder
 --- / -------- \
Engine------ Game
--- | -------  | ------- \
Stuff----Default ---Custom Game

**Comment by milkyroute** [comment]
It's a great idea I approve! However since I don't want to delay the 0.16, I will do it after releasing this version.

**Comment by PyroFlareX** [comment]
When I get time to understand the code base, I'll send in a few PR's to start on this. Also, a format for data types needs to be planned out.

**Comment by milkyroute** [comment]
As said in the pull request #148, I won't completely isolate the engine from the game, but I've separated the abstract objects from the concrete ones. The tools have also been separated from the objects.
